### ISSUE TITLE
Quest A Curse Upon Both of Your Clans!

### ISSUE THREAD

**Issue by Rajha93** [BurnedLand/BurnedLand-Report#12]
Rajha,ally night elf 

missione A Curse Upon Both of Your Clans!
il Wicked Strong Fetish https://tbc.wowhead.com/item=30479/wicked-strong-fetish non funziona vicino ai  bloodmaul outpost

https://www.wowhead.com/quest=10544/a-curse-upon-both-of-your-clans

**Comment by BurnedLand** [comment]
Fixed
