### ISSUE TITLE
Quest Fervor of the frostborn

### ISSUE THREAD

**Issue by Rajha93** [BurnedLand/BurnedLand-Report#16]
rajha,ally night elf

quest Fervor of the Frostborn

The iron Watcher non ce

https://www.wowhead.com/it/quest=12874/fervor-of-the-frostborn

![WoWScrnShot_091922_165833](https://user-images.githubusercontent.com/113799005/191048491-15bff875-cf0b-4db5-8a25-95cb84dfd612.jpg)

**Comment by BurnedLand** [comment]
Fixed
