### ISSUE TITLE
time lost protodrake

### ISSUE THREAD

**Issue by Rajha93** [BurnedLand/BurnedLand-Report#18]
Rajha ally

il time lost proto drake sembra non esistere

https://it.wowhead.com/npc=32491/proto-draco-senza-tempo

![WoWScrnShot_091922_171419](https://user-images.githubusercontent.com/113799005/191051838-aeccd862-a183-4d7b-807e-689339d6a935.jpg)

vedere chat nella foto

**Comment by BurnedLand** [comment]
@Rajha93 Verifica che gli id siano corrispondenti :)
