### ISSUE TITLE
Quest The Battle for Andorhal

### ISSUE THREAD

**Issue by BurnedLand** [BurnedLand/BurnedLand-Report#31]
[Player Name and Faction] Maze, Alliance

[Type: Item/Quest/Spell/Npc and Name ] Quest, The Battle for Andorhal

[Describe the bug] L'npc "Guthrum Thunderfist" non offre il volo per Andorhal 

[Wowhead link ] (https://www.wowhead.com/quest=28505/the-battle-for-andorhal)

**Comment by Maze003** [comment]
Fixed
